version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JDBC_URL : jdbc:mysql://sgh-db:3306/sgh
      JDBC_USERNAME: root
      JDBC_PASSWORD: root
      JDBC_DRIVERCLASSNAME: com.mysql.jdbc.Driver
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    restart: on-failure

  db:
    image: mysql:8
    container_name: sgh-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: sgh
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

